server:
  port: 80

spring:
  application:
    name: service-gateway
  cloud:
    nacos:
      discovery:
        server-addr: http://192.168.47.130:8848
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: user-service
          uri: lb://user-service
          predicates:
            - Path=/*/acl/**
        - id: commodity-server
          uri: lb://commodity-server
          predicates:
            - Path=/*/commodity/**,/*/config/**,/*/purchase/**
        - id: order-server
          uri: lb://order-server
          predicates:
            - Path=/*/order/**
#        - id: commodity-server
#          uri: lb://commodity-server
#          predicates:
#            - Path=/*/commodity/**




  redis:
    host: 192.168.47.130
    port: 6379
    database: 0
    timeout: 1800000
#  session:
#    store-type: redis